services:
  backend:
    build: ./backend
    networks:
      - myapp_network
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    ports:
      -"3000:3000"
    networks:
      - myapp_network

  networks:
    myapp_network:
      driver: bridge